-- Comfytosh Theme for Neovim: do more, get comfy
-- Flavors: "screen" (dark) and "case" (light). Generated from tokens.json.
local M = {}

M.palettes = {
  screen = {
    bg = "#282e2b",
    bg_raised = "#343b37",
    bg_sunken = "#222623",
    bg_overlay = "#3c4641",
    border = "#3c4641",
    border_strong = "#7e8f85",
    ink = "#d6e8c8",
    ink_muted = "#bac1b8",
    accent = "#ff773d",
    accent_ink = "#ff773d",
    on_accent = "#282e2b",
    focus = "#7cd3a2",
    cursor = "#c5f899",
    selection = "#3a5245",
    line_highlight = "#333936",
    match = "#5d5c49",
    success = "#7cd3a2",
    warning = "#e59f71",
    danger = "#ff6b6b",
    info = "#8fb3dd",
    hint = "#7fcfd4",
    diff_add = "#36493e",
    diff_remove = "#4b3835",
    diff_change = "#394348",
    keyword = "#b9a3d9",
    string = "#7cd3a2",
    func = "#8fb3dd",
    type = "#e8d595",
    number = "#ff773d",
    constant = "#e594b4",
    property = "#7fcfd4",
    tag = "#ff6b6b",
    operator = "#bac1b8",
    comment = "#bac1b8",
    term_bg = "#222623",
    ansi0 = "#3c4641",
    ansi1 = "#ff6b6b",
    ansi2 = "#7cd3a2",
    ansi3 = "#e8d595",
    ansi4 = "#8fb3dd",
    ansi5 = "#b9a3d9",
    ansi6 = "#7fcfd4",
    ansi7 = "#bac1b8",
    ansi8 = "#7e8f85",
    ansi9 = "#ff6b6b",
    ansi10 = "#7cd3a2",
    ansi11 = "#e8d595",
    ansi12 = "#8fb3dd",
    ansi13 = "#b9a3d9",
    ansi14 = "#7fcfd4",
    ansi15 = "#d6e8c8",
  },
  case = {
    bg = "#e3dac9",
    bg_raised = "#ece7de",
    bg_sunken = "#c7c4bf",
    bg_overlay = "#ece7de",
    border = "#c7c4bf",
    border_strong = "#555d50",
    ink = "#282e2b",
    ink_muted = "#4b5247",
    accent = "#ff773d",
    accent_ink = "#ae3400",
    on_accent = "#282e2b",
    focus = "#ae3400",
    cursor = "#ae3400",
    selection = "#d6e8c8",
    line_highlight = "#d9d1c1",
    match = "#e8d595",
    success = "#22643f",
    warning = "#91491a",
    danger = "#ac1a23",
    info = "#2f5f93",
    hint = "#1d6368",
    diff_add = "#c6c8b4",
    diff_remove = "#dbbdb0",
    diff_change = "#c8c8c1",
    keyword = "#6a4c97",
    string = "#22643f",
    func = "#2f5f93",
    type = "#91491a",
    number = "#ae3400",
    constant = "#8f3558",
    property = "#1d6368",
    tag = "#ac1a23",
    operator = "#4b5247",
    comment = "#4b5247",
    term_bg = "#ece7de",
    ansi0 = "#282e2b",
    ansi1 = "#ac1a23",
    ansi2 = "#22643f",
    ansi3 = "#91491a",
    ansi4 = "#2f5f93",
    ansi5 = "#6a4c97",
    ansi6 = "#1d6368",
    ansi7 = "#7e8f85",
    ansi8 = "#4b5247",
    ansi9 = "#ac1a23",
    ansi10 = "#22643f",
    ansi11 = "#91491a",
    ansi12 = "#2f5f93",
    ansi13 = "#6a4c97",
    ansi14 = "#1d6368",
    ansi15 = "#c7c4bf",
  },
}

M.options = { transparent = false, italic_comments = true }

function M.setup(opts)
  M.options = vim.tbl_extend("force", M.options, opts or {})
end

function M.load(flavor, opts)
  local o = vim.tbl_extend("force", M.options, opts or {})
  local p = M.palettes[flavor]
  if not p then
    error("comfytosh: unknown flavor " .. tostring(flavor) .. " (use \"screen\" or \"case\")")
  end

  vim.cmd("hi clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.o.termguicolors = true
  vim.o.background = (flavor == "case") and "light" or "dark"
  vim.g.colors_name = "comfytosh-" .. flavor

  local bg = o.transparent and "NONE" or p.bg
  local side = o.transparent and "NONE" or p.bg_raised

  local g = {
    Normal = { fg = p.ink, bg = bg },
    NormalNC = { fg = p.ink, bg = bg },
    NormalFloat = { fg = p.ink, bg = p.bg_overlay },
    FloatBorder = { fg = p.border_strong, bg = p.bg_overlay },
    FloatTitle = { fg = p.accent_ink, bg = p.bg_overlay, bold = true },
    Cursor = { fg = p.bg, bg = p.cursor },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    TermCursor = { link = "Cursor" },
    CursorLine = { bg = p.line_highlight },
    CursorColumn = { bg = p.line_highlight },
    ColorColumn = { bg = p.bg_raised },
    CursorLineNr = { fg = p.ink, bold = true },
    LineNr = { fg = p.ink_muted },
    SignColumn = { fg = p.ink_muted, bg = bg },
    FoldColumn = { fg = p.ink_muted, bg = bg },
    Folded = { fg = p.ink_muted, bg = p.bg_raised },
    Visual = { bg = p.selection },
    VisualNOS = { bg = p.selection },
    Search = { fg = p.ink, bg = p.match },
    IncSearch = { fg = p.on_accent, bg = p.accent },
    CurSearch = { fg = p.on_accent, bg = p.accent },
    Substitute = { fg = p.on_accent, bg = p.accent },
    MatchParen = { bg = p.selection, bold = true },
    NonText = { fg = p.border_strong },
    EndOfBuffer = { fg = bg },
    Whitespace = { fg = p.border },
    SpecialKey = { fg = p.border_strong },
    Conceal = { fg = p.ink_muted },
    Directory = { fg = p.func },
    Title = { fg = p.func, bold = true },
    ErrorMsg = { fg = p.danger, bold = true },
    WarningMsg = { fg = p.warning },
    ModeMsg = { fg = p.ink, bold = true },
    MoreMsg = { fg = p.success },
    Question = { fg = p.hint },
    WinSeparator = { fg = p.border },
    VertSplit = { link = "WinSeparator" },
    StatusLine = { fg = p.ink_muted, bg = p.bg_sunken },
    StatusLineNC = { fg = p.ink_muted, bg = p.bg_sunken },
    TabLine = { fg = p.ink_muted, bg = p.bg_sunken },
    TabLineFill = { bg = p.bg_sunken },
    TabLineSel = { fg = p.ink, bg = p.bg, bold = true },
    WinBar = { fg = p.ink_muted, bg = bg },
    WinBarNC = { fg = p.ink_muted, bg = bg },
    Pmenu = { fg = p.ink, bg = p.bg_overlay },
    PmenuSel = { bg = p.selection, bold = true },
    PmenuSbar = { bg = p.bg_raised },
    PmenuThumb = { bg = p.border_strong },
    WildMenu = { link = "PmenuSel" },
    DiffAdd = { bg = p.diff_add },
    DiffChange = { bg = p.diff_change },
    DiffDelete = { bg = p.diff_remove },
    DiffText = { bg = p.selection },
    Added = { fg = p.success },
    Changed = { fg = p.info },
    Removed = { fg = p.danger },
    SpellBad = { sp = p.danger, undercurl = true },
    SpellCap = { sp = p.warning, undercurl = true },
    SpellLocal = { sp = p.info, undercurl = true },
    SpellRare = { sp = p.hint, undercurl = true },

    DiagnosticError = { fg = p.danger },
    DiagnosticWarn = { fg = p.warning },
    DiagnosticInfo = { fg = p.info },
    DiagnosticHint = { fg = p.hint },
    DiagnosticOk = { fg = p.success },
    DiagnosticVirtualTextError = { fg = p.danger, bg = p.diff_remove },
    DiagnosticVirtualTextWarn = { fg = p.warning, bg = p.match },
    DiagnosticVirtualTextInfo = { fg = p.info, bg = p.diff_change },
    DiagnosticVirtualTextHint = { fg = p.hint, bg = p.diff_change },
    DiagnosticUnderlineError = { sp = p.danger, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.warning, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.info, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.hint, undercurl = true },
    DiagnosticUnnecessary = { fg = p.ink_muted },
    LspReferenceText = { bg = p.diff_change },
    LspReferenceRead = { bg = p.diff_change },
    LspReferenceWrite = { bg = p.diff_change, underline = true },
    LspInlayHint = { fg = p.ink_muted, bg = p.bg_raised },
    LspSignatureActiveParameter = { fg = p.accent_ink, bold = true },

    Comment = { fg = p.comment, italic = o.italic_comments },
    Constant = { fg = p.constant },
    String = { fg = p.string },
    Character = { fg = p.string },
    Number = { fg = p.number },
    Boolean = { fg = p.constant },
    Float = { fg = p.number },
    Identifier = { fg = p.ink },
    Function = { fg = p.func },
    Statement = { fg = p.keyword },
    Conditional = { fg = p.keyword },
    Repeat = { fg = p.keyword },
    Label = { fg = p.constant },
    Operator = { fg = p.operator },
    Keyword = { fg = p.keyword },
    Exception = { fg = p.keyword },
    PreProc = { fg = p.keyword },
    Include = { fg = p.keyword },
    Define = { fg = p.keyword },
    Macro = { fg = p.func },
    PreCondit = { fg = p.keyword },
    Type = { fg = p.type },
    StorageClass = { fg = p.keyword },
    Structure = { fg = p.type },
    Typedef = { fg = p.type },
    Special = { fg = p.constant },
    SpecialChar = { fg = p.constant },
    Tag = { fg = p.tag },
    Delimiter = { fg = p.operator },
    SpecialComment = { fg = p.comment, italic = o.italic_comments },
    Debug = { fg = p.constant },
    Underlined = { fg = p.accent_ink, underline = true },
    Ignore = { fg = p.ink_muted },
    Error = { fg = p.danger },
    Todo = { fg = p.on_accent, bg = p.accent, bold = true },

    ["@variable"] = { fg = p.ink },
    ["@variable.builtin"] = { fg = p.constant },
    ["@variable.parameter"] = { fg = p.ink },
    ["@variable.member"] = { fg = p.property },
    ["@property"] = { fg = p.property },
    ["@constant"] = { fg = p.constant },
    ["@constant.builtin"] = { fg = p.constant },
    ["@constant.macro"] = { fg = p.constant },
    ["@module"] = { fg = p.type },
    ["@label"] = { fg = p.constant },
    ["@string"] = { fg = p.string },
    ["@string.escape"] = { fg = p.constant },
    ["@string.regexp"] = { fg = p.property },
    ["@string.special"] = { fg = p.constant },
    ["@character"] = { fg = p.string },
    ["@number"] = { fg = p.number },
    ["@number.float"] = { fg = p.number },
    ["@boolean"] = { fg = p.constant },
    ["@type"] = { fg = p.type },
    ["@type.builtin"] = { fg = p.type },
    ["@type.definition"] = { fg = p.type },
    ["@attribute"] = { fg = p.property },
    ["@constructor"] = { fg = p.type },
    ["@function"] = { fg = p.func },
    ["@function.builtin"] = { fg = p.func },
    ["@function.call"] = { fg = p.func },
    ["@function.method"] = { fg = p.func },
    ["@function.method.call"] = { fg = p.func },
    ["@function.macro"] = { fg = p.func },
    ["@keyword"] = { fg = p.keyword },
    ["@keyword.function"] = { fg = p.keyword },
    ["@keyword.return"] = { fg = p.keyword },
    ["@keyword.operator"] = { fg = p.keyword },
    ["@keyword.import"] = { fg = p.keyword },
    ["@keyword.exception"] = { fg = p.keyword },
    ["@keyword.conditional"] = { fg = p.keyword },
    ["@keyword.repeat"] = { fg = p.keyword },
    ["@operator"] = { fg = p.operator },
    ["@punctuation"] = { fg = p.operator },
    ["@punctuation.bracket"] = { fg = p.operator },
    ["@punctuation.delimiter"] = { fg = p.operator },
    ["@punctuation.special"] = { fg = p.constant },
    ["@comment"] = { fg = p.comment, italic = o.italic_comments },
    ["@comment.documentation"] = { fg = p.comment, italic = o.italic_comments },
    ["@comment.error"] = { fg = p.danger, bold = true },
    ["@comment.warning"] = { fg = p.warning, bold = true },
    ["@comment.todo"] = { fg = p.on_accent, bg = p.accent, bold = true },
    ["@comment.note"] = { fg = p.info, bold = true },
    ["@tag"] = { fg = p.tag },
    ["@tag.attribute"] = { fg = p.property },
    ["@tag.delimiter"] = { fg = p.operator },
    ["@markup.heading"] = { fg = p.func, bold = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.link"] = { fg = p.accent_ink },
    ["@markup.link.url"] = { fg = p.hint, underline = true },
    ["@markup.raw"] = { fg = p.string },
    ["@markup.quote"] = { fg = p.comment, italic = true },
    ["@markup.list"] = { fg = p.keyword },
    ["@diff.plus"] = { fg = p.success },
    ["@diff.minus"] = { fg = p.danger },
    ["@diff.delta"] = { fg = p.info },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.enumMember"] = { fg = p.constant },

    GitSignsAdd = { fg = p.success },
    GitSignsChange = { fg = p.info },
    GitSignsDelete = { fg = p.danger },
    TelescopeNormal = { fg = p.ink, bg = p.bg_overlay },
    TelescopeBorder = { fg = p.border_strong, bg = p.bg_overlay },
    TelescopeTitle = { fg = p.accent_ink, bold = true },
    TelescopeSelection = { bg = p.selection },
    TelescopeMatching = { fg = p.accent_ink, bold = true },
    TelescopePromptPrefix = { fg = p.accent_ink },
    CmpItemAbbr = { fg = p.ink },
    CmpItemAbbrMatch = { fg = p.accent_ink, bold = true },
    CmpItemAbbrDeprecated = { fg = p.ink_muted, strikethrough = true },
    CmpItemKind = { fg = p.type },
    CmpItemMenu = { fg = p.ink_muted },
    NeoTreeNormal = { fg = p.ink, bg = side },
    NeoTreeNormalNC = { fg = p.ink, bg = side },
    NeoTreeDirectoryName = { fg = p.func },
    NeoTreeDirectoryIcon = { fg = p.func },
    NeoTreeRootName = { fg = p.accent_ink, bold = true },
    NeoTreeGitAdded = { fg = p.success },
    NeoTreeGitModified = { fg = p.info },
    NeoTreeGitDeleted = { fg = p.danger },
    NvimTreeNormal = { fg = p.ink, bg = side },
    NvimTreeFolderName = { fg = p.func },
    NvimTreeRootFolder = { fg = p.accent_ink, bold = true },
    IblIndent = { fg = p.border },
    IblScope = { fg = p.border_strong },
    WhichKey = { fg = p.accent_ink },
    WhichKeyDesc = { fg = p.ink },
    WhichKeyGroup = { fg = p.func },
    WhichKeySeparator = { fg = p.ink_muted },
  }

  for name, val in pairs(g) do
    vim.api.nvim_set_hl(0, name, val)
  end

  for i = 0, 15 do
    vim.g["terminal_color_" .. i] = p["ansi" .. i]
  end
end

return M
