# Comfytosh Case
# Comfytosh Theme: do more, get comfy

[colors.primary]
background = "#ece7de"
foreground = "#282e2b"

[colors.cursor]
text = "#ece7de"
cursor = "#ae3400"

[colors.selection]
text = "#282e2b"
background = "#d6e8c8"

[colors.normal]
black = "#282e2b"
red = "#ac1a23"
green = "#22643f"
yellow = "#91491a"
blue = "#2f5f93"
magenta = "#6a4c97"
cyan = "#1d6368"
white = "#7e8f85"

[colors.bright]
black = "#4b5247"
red = "#ac1a23"
green = "#22643f"
yellow = "#91491a"
blue = "#2f5f93"
magenta = "#6a4c97"
cyan = "#1d6368"
white = "#c7c4bf"
