# Comfytosh Screen
# Comfytosh Theme: do more, get comfy

[colors.primary]
background = "#222623"
foreground = "#d6e8c8"

[colors.cursor]
text = "#222623"
cursor = "#c5f899"

[colors.selection]
text = "#d6e8c8"
background = "#364c3f"

[colors.normal]
black = "#3c4641"
red = "#ff6b6b"
green = "#7cd3a2"
yellow = "#e8d595"
blue = "#8fb3dd"
magenta = "#b9a3d9"
cyan = "#7fcfd4"
white = "#bac1b8"

[colors.bright]
black = "#7e8f85"
red = "#ff6b6b"
green = "#7cd3a2"
yellow = "#e8d595"
blue = "#8fb3dd"
magenta = "#b9a3d9"
cyan = "#7fcfd4"
white = "#d6e8c8"
