# vim:ft=kitty
# Comfytosh Screen
# Comfytosh Theme: do more, get comfy

foreground #d6e8c8
background #222623
selection_foreground #d6e8c8
selection_background #364c3f

cursor #c5f899
cursor_text_color #222623
url_color #7fcfd4

active_border_color #ff773d
inactive_border_color #7e8f85
bell_border_color #e59f71

active_tab_foreground #282e2b
active_tab_background #ff773d
inactive_tab_foreground #bac1b8
inactive_tab_background #343b37
tab_bar_background #222623

color0 #3c4641
color1 #ff6b6b
color2 #7cd3a2
color3 #e8d595
color4 #8fb3dd
color5 #b9a3d9
color6 #7fcfd4
color7 #bac1b8
color8 #7e8f85
color9 #ff6b6b
color10 #7cd3a2
color11 #e8d595
color12 #8fb3dd
color13 #b9a3d9
color14 #7fcfd4
color15 #d6e8c8
