#!/usr/bin/env python3
"""Build the Comfytosh Theme landing page into _site/.

Standard library only. The page is data driven:
  - palette.json  -> the theme colours used by the examples and the palette section
  - ports.json    -> the ports grid, the downloads and the wanted list
  - site/vendor/comfytosh/tokens.json -> tokens.css for the Comfytosh design system

Run from the repository root:  python3 scripts/build_site.py [--out _site]
"""
import argparse
import html
import json
import os
import shutil
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
VENDOR = SITE / "vendor" / "comfytosh"
REPO = "https://github.com/" + os.environ.get("GITHUB_REPOSITORY", "vstrofago/comfytosh")
BRANCH = os.environ.get("SITE_BRANCH", "main")

FAMILIES = [
    ("case", "Case plastics", "The beige machine. Grounds of the Case flavor."),
    ("crt", "Screen glass", "Cabinet and glass greys. Grounds of the Screen flavor."),
    ("phosphor", "Phosphor greens", "The terminal glow: strings, success and the cursor."),
    ("amber", "Amber", "The amber monitor and warm earth."),
    ("signal", "Signal", "The loudest colours. One per view."),
    ("comfy", "Comfy cool hues", "Blue, purple, cyan and rose for a full syntax theme."),
    ("deep", "Deep", "Darker twins that hold 4.5:1 on beige. Text on Case."),
]
CATEGORY_COLOR = {
    "editor": "comfy-lilac",
    "terminal": "phosphor-celadon",
    "cli": "amber-custard",
    "app": "comfy-periwinkle",
    "desktop": "comfy-rose",
}
# The design system ships these weights; tokens.json lists the .ttf names, the site serves .woff2.
SHIPPED_FONTS = {
    "Geist-Regular", "Geist-Medium", "Geist-SemiBold", "Geist-Italic",
    "GeistMono-Regular", "GeistMono-Medium", "GeistMono-SemiBold", "GeistMono-Bold",
    "GeistPixel-Square",
    "IBMPlexSerif-Light", "IBMPlexSerif-Regular", "IBMPlexSerif-Italic", "IBMPlexSerif-SemiBold",
}

esc = html.escape


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


# ── tokens.css for the design system, compiled the way the design system page does ──

def css_value(value):
    if isinstance(value, str) and value.startswith("{") and value.endswith("}"):
        return "var(--%s)" % value[1:-1]
    return value


def compile_tokens(tokens):
    themes = [t["id"] for t in tokens["color"]["themes"]]
    first = themes[0]

    def per_theme(entries):
        base, extra = [], {t: [] for t in themes[1:]}
        for tok in entries:
            v = tok["value"]
            if isinstance(v, str):
                base.append((tok["name"], css_value(v)))
                continue
            fv = v.get(first, next(iter(v.values())))
            base.append((tok["name"], css_value(fv)))
            for t in themes[1:]:
                if t in v and v[t] != fv:
                    extra[t].append((tok["name"], css_value(v[t])))
        return base, extra

    cbase, cextra = per_theme(tokens["color"]["tokens"])
    sbase, sextra = per_theme(tokens.get("shadow", {}).get("tokens", []))
    out = ["/* Generated by scripts/build_site.py from site/vendor/comfytosh/tokens.json. Do not edit. */"]
    out.append(':root, [data-theme="%s"] {' % first)
    out += ["  --%s: %s;" % kv for kv in cbase + sbase]
    out.append("}")
    for t in themes[1:]:
        out.append('[data-theme="%s"] {' % t)
        out += ["  --%s: %s;" % kv for kv in cextra[t] + sextra[t]]
        out.append("}")
    out.append(":root {")
    for fam in ("spacing", "radius"):
        out += ["  --%s: %s;" % (t["name"], t["value"]) for t in tokens.get(fam, {}).get("tokens", [])]
    for key, stack in tokens["type"]["families"].items():
        out.append("  --font-%s: %s;" % (key, stack))
    out.append("}")
    for font in tokens["type"]["fonts"]:
        stem = Path(font["file"]).stem
        if stem not in SHIPPED_FONTS:
            continue
        out.append(
            '@font-face { font-family: "%s"; src: url("fonts/%s.woff2") format("woff2"); '
            "font-weight: %s; font-style: %s; font-display: swap; }"
            % (font["family"], stem, font["weight"], font.get("style", "normal"))
        )
    return "\n".join(out) + "\n"


# ── theme.css: the theme's own colours, from palette.json ──

def compile_theme(palette):
    out = ["/* Generated by scripts/build_site.py from palette.json. Do not edit. */", ":root {"]
    out += ["  --%s: %s;" % kv for kv in palette["primitives"].items()]
    out.append("}")
    for fid, flavor in palette["flavors"].items():
        out.append('.th[data-flavor="%s"] {' % fid)
        out += ["  --th-%s: %s;" % kv for kv in flavor["roles"].items()]
        out.append("}")
    return "\n".join(out) + "\n"


# ── HTML fragments ──

def render_palette(palette):
    prims = palette["primitives"]
    blocks = []
    for prefix, title, note in FAMILIES:
        names = [n for n in prims if n.split("-")[0] == prefix]
        if not names:
            continue
        chips = []
        for n in names:
            hx = prims[n]
            chips.append(
                '<div class="chip"><button class="chip__cap" style="--c:{hx}" data-copy="{hx}" '
                'aria-label="Copy {n} {hx}"></button><span class="chip__name">{n}</span>'
                '<span class="chip__hex">{hx}</span></div>'.format(n=esc(n), hx=esc(hx))
            )
        blocks.append(
            '<section class="family"><header class="family__head"><h3>{t}</h3><p>{note}</p></header>'
            '<div class="chips">{chips}</div></section>'.format(t=esc(title), note=esc(note), chips="".join(chips))
        )
    return "\n".join(blocks)


def render_filters(registry):
    counts = {}
    for p in registry["ports"]:
        counts[p["category"]] = counts.get(p["category"], 0) + 1
    pills = ['<button class="ct-pill ct-pill--tangerine" type="button" aria-pressed="true" data-filter="all">All <span class="count">%d</span></button>' % len(registry["ports"])]
    for key, label in registry["categories"].items():
        if key in counts:
            pills.append(
                '<button class="ct-pill" type="button" aria-pressed="false" data-filter="{k}">{l} <span class="count">{c}</span></button>'.format(
                    k=esc(key), l=esc(label), c=counts[key]
                )
            )
    return "\n".join(pills)


def render_ports(registry):
    cats = registry["categories"]
    tiles = []
    for p in sorted(registry["ports"], key=lambda p: p["name"].lower()):
        aliases = p.get("aliases", [])
        search = " ".join([p["name"], p["id"], cats[p["category"]]] + aliases).lower()
        also = '<p class="port__also">Also {}</p>'.format(esc(", ".join(aliases))) if aliases else ""
        by = ", ".join('<a href="https://github.com/{u}">@{u}</a>'.format(u=esc(m)) for m in p.get("maintainers", []))
        by = '<span class="port__by">by {}</span>'.format(by) if by else '<span class="port__by port__by--none">needs a maintainer</span>'
        tiles.append(
            """<article class="port" data-cat="{cat}" data-search="{search}">
  <div class="port__head"><span class="port__mark" style="--pm:var(--{color})" aria-hidden="true">{initial}</span>
    <div><h3 class="port__name"><a href="{home}">{name}</a></h3><span class="port__cat">{catlabel}</span></div></div>
  {also}
  <details class="port__how"><summary>How to install</summary><p>{install}</p></details>
  <div class="port__foot"><a class="ct-key ct-key--sm" href="downloads/comfytosh-{id}.zip" download><span data-ic="download"></span>Download</a>
    <a class="port__src" href="{repo}/tree/{branch}/{path}">Source</a>{by}</div>
</article>""".format(
                cat=esc(p["category"]), search=esc(search), color=CATEGORY_COLOR.get(p["category"], "crt-ash"),
                initial=esc(p["name"][0].upper()), home=esc(p.get("homepage", "#")), name=esc(p["name"]),
                catlabel=esc(cats[p["category"]].rstrip("s") if p["category"] != "cli" else "Command line"),
                also=also, install=esc(p["install"]), id=esc(p["id"]), repo=REPO, branch=BRANCH,
                path=esc(p["path"]), by=by,
            )
        )
    tiles.append(
        """<article class="port port--request" data-cat="all" data-search="">
  <h3 class="port__name">Your tool here</h3>
  <p>Comfytosh grows one port at a time. Ask for one, or build it with the guide.</p>
  <div class="port__foot"><a class="ct-key ct-key--sm" href="{repo}/issues/new?template=port-request.yml"><span data-ic="plus"></span>Request a port</a>
    <a class="port__src" href="{repo}/blob/{branch}/CONTRIBUTING.md">Build it</a></div>
</article>""".format(repo=REPO, branch=BRANCH)
    )
    return "\n".join(tiles)


def render_wanted(registry):
    tags = []
    for name in registry.get("wanted", []):
        title = "[Port]: " + name
        href = "{}/issues/new?template=port-request.yml&title={}".format(REPO, title.replace(" ", "+").replace(":", "%3A").replace("[", "%5B").replace("]", "%5D"))
        tags.append('<li><a class="ct-tag ct-tag--sm" href="{h}"><span data-ic="plus"></span>{n}</a></li>'.format(h=esc(href), n=esc(name)))
    return "\n".join(tags)


# ── build ──

def build(out):
    palette = load(ROOT / "palette.json")
    registry = load(ROOT / "ports.json")
    tokens = load(VENDOR / "tokens.json")

    if out.exists():
        shutil.rmtree(out)
    shutil.copytree(SITE, out, ignore=shutil.ignore_patterns("*.json", "*.md"))
    (out / "vendor" / "comfytosh" / "tokens.css").write_text(compile_tokens(tokens), encoding="utf-8")
    (out / "assets" / "theme.css").write_text(compile_theme(palette), encoding="utf-8")
    (out / ".nojekyll").write_text("", encoding="utf-8")

    for name in ("palette.json", "ports.json"):
        shutil.copy2(ROOT / name, out / name)
    walls = out / "wallpapers"
    walls.mkdir(exist_ok=True)
    for png in sorted((ROOT / "wallpapers").glob("*.png")):
        shutil.copy2(png, walls / png.name)

    downloads = out / "downloads"
    downloads.mkdir(exist_ok=True)
    with zipfile.ZipFile(downloads / "comfytosh-ports.zip", "w", zipfile.ZIP_DEFLATED) as everything:
        for port in registry["ports"]:
            folder = ROOT / port["path"]
            files = sorted(f for f in folder.rglob("*") if f.is_file())
            with zipfile.ZipFile(downloads / ("comfytosh-%s.zip" % port["id"]), "w", zipfile.ZIP_DEFLATED) as one:
                for f in files:
                    arc = f.relative_to(ROOT).as_posix()
                    one.write(f, arc)
                    everything.write(f, arc)
        everything.write(ROOT / "palette.json", "palette.json")

    page = (SITE / "index.html").read_text(encoding="utf-8")
    replacements = {
        "<!-- @palette -->": render_palette(palette),
        "<!-- @filters -->": render_filters(registry),
        "<!-- @ports -->": render_ports(registry),
        "<!-- @wanted -->": render_wanted(registry),
        "{{port_count}}": str(len(registry["ports"])),
        "{{colour_count}}": str(len(palette["primitives"])),
        "{{repo}}": REPO,
        "{{branch}}": BRANCH,
    }
    for key, value in replacements.items():
        if key not in page:
            raise SystemExit("site/index.html is missing the placeholder " + key)
        page = page.replace(key, value)
    (out / "index.html").write_text(page, encoding="utf-8")
    print("Built %s: %d ports, %d colours" % (out.relative_to(ROOT) if out.is_relative_to(ROOT) else out, len(registry["ports"]), len(palette["primitives"])))


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=str(ROOT / "_site"))
    build(Path(ap.parse_args().out).resolve())
