# Comfytosh Screen
# Comfytosh Theme: do more, get comfy
set -g status-style "bg=#222623,fg=#bac1b8"
set -g status-left "#[bg=#ff773d,fg=#282e2b,bold] #S #[default] "
set -g status-right "#[fg=#bac1b8] %H:%M "
set -g window-status-format " #I #W "
set -g window-status-style "bg=#343b37,fg=#bac1b8"
set -g window-status-current-format " #I #W "
set -g window-status-current-style "bg=#ff773d,fg=#282e2b,bold"
set -g window-status-activity-style "fg=#e59f71"
set -g window-status-bell-style "fg=#ff6b6b,bold"
set -g pane-border-style "fg=#7e8f85"
set -g pane-active-border-style "fg=#ff773d"
set -g message-style "bg=#3c4641,fg=#d6e8c8"
set -g message-command-style "bg=#3c4641,fg=#d6e8c8"
set -g mode-style "bg=#3a5245,fg=#d6e8c8"
set -g clock-mode-colour "#ff773d"
set -g display-panes-colour "#bac1b8"
set -g display-panes-active-colour "#ff773d"
