# Comfytosh Case
# Comfytosh Theme: do more, get comfy
set -g status-style "bg=#c7c4bf,fg=#4b5247"
set -g status-left "#[bg=#ff773d,fg=#282e2b,bold] #S #[default] "
set -g status-right "#[fg=#4b5247] %H:%M "
set -g window-status-format " #I #W "
set -g window-status-style "bg=#ece7de,fg=#4b5247"
set -g window-status-current-format " #I #W "
set -g window-status-current-style "bg=#ff773d,fg=#282e2b,bold"
set -g window-status-activity-style "fg=#91491a"
set -g window-status-bell-style "fg=#ac1a23,bold"
set -g pane-border-style "fg=#555d50"
set -g pane-active-border-style "fg=#ae3400"
set -g message-style "bg=#ece7de,fg=#282e2b"
set -g message-command-style "bg=#ece7de,fg=#282e2b"
set -g mode-style "bg=#d6e8c8,fg=#282e2b"
set -g clock-mode-colour "#ae3400"
set -g display-panes-colour "#4b5247"
set -g display-panes-active-colour "#ae3400"
